services:
  website:
    image: "${NEXT_APP_WEBSITE_IMAGE}"
    container_name: website
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT:-587}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      NEXT_PUBLIC_CLOUDFLARE_SITE_KEY: ${NEXT_PUBLIC_CLOUDFLARE_SITE_KEY}
      CLOUDFLARE_SECRET: ${CLOUDFLARE_SECRET}
      NEXT_TELEMETRY_DISABLED: 1
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    secrets:
      - ssl_cert
      - ssl_key
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      cache_from:
        - "${NEXT_APP_NGINX_IMAGE}"
    container_name: nginx
    image: "${NEXT_APP_NGINX_IMAGE}"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - website
    restart: always
    networks:
      - app-network
    volumes:
      - certbot-webroot:/var/www/certbot:rw

networks:
  app-network:
    driver: bridge
volumes:
  certbot-webroot:
    driver: local
secrets:
  ssl_cert:
    file: ./certificate.pem
  ssl_key:
    file: ./private_key.pem
